# Generated by Django 5.1.7 on 2025-06-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_listing_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.CharField(
                default="https://static.vecteezy.com/system/resources/thumbnails/004/141/669/small_2x/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg",
                max_length=100,
                null=True,
            ),
        ),
    ]
