# Generated by Django 5.1.7 on 2025-07-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_listing_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.CharField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdD7G7FFg1UKZFXhyP45b4AvY-qKEFvfjj3w&s",
                max_length=200,
                null=True,
            ),
        ),
    ]
