# Generated by Django 5.1.7 on 2025-07-04 19:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_alter_listing_category_alter_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
