# Generated by Django 5.1.7 on 2025-07-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_comment_added_at_alter_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="winner",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
